[global]
quit = { keys = ["q", "ctrl+c"], desc = "<quit>", show = true }
change_server = { keys = ["c"], desc = "<change endpoint>", show = true }
filter = { keys = ["/"], desc = "<filter>", show = true }
clear_filter = { keys = [
    "escape",
    "ctrl+left_square_bracket",
], desc = "<clr filter>", show = false }
refresh_models = { keys = ["r"], desc = "<refresh models>", show = true }
test_connection = { keys = ["*"], desc = "<test connection>", show = false }
show_keybinds = { keys = ["?"], desc = "<hotkeys>", show = true }

focus_left = { keys = [
    "ctrl+h",
    "ctrl+left",
], desc = "Focus pane left", show = false }
focus_right = { keys = [
    "ctrl+l",
    "ctrl+right",
], desc = "Focus pane right", show = false }
focus_up = { keys = [
    "ctrl+k",
    "ctrl+up",
], desc = "Focus header log", show = false }
focus_down = { keys = [
    "ctrl+j",
    "ctrl+down",
], desc = "Focus main area", show = false }

[tables]
cursor_up = { keys = ["up", "k", "alt+p"], desc = "<cursor up>", show = false }
cursor_down = { keys = [
    "down",
    "j",
    "alt+n",
], desc = "<cursor down>", show = false }
sort_on_name = { keys = ["n"], desc = "<sort name>", show = true }
sort_on_size = { keys = ["s"], desc = "<sort size>", show = true }

[loaded_models]
unload_selected = { keys = ["u"], desc = "<unload selected>", show = true }
unload_all = { keys = ["U"], desc = "<unload all>", show = true }
select_model = { keys = ["space"], desc = "<select model>", show = false }
toggle_group = { keys = ["x"], desc = "<select group>", show = false }
select_down = { keys = [
    "down",
    "j",
    "alt+n",
], desc = "<cursor down>", show = false }
select_up = { keys = ["up", "k", "alt+p"], desc = "<cursor up>", show = false }

[action_log]
scroll_up = { keys = ["up", "k", "alt+p"], desc = "<scroll up>", show = false }
scroll_down = { keys = [
    "down",
    "j",
    "alt+n",
], desc = "<scroll down>", show = false }

[sever_select]
quit = { keys = ["q", "escape"], desc = "<cancel>", show = true }
connect_input_submit = { keys = ["c"], desc = "<connect>", show = true }
scan_network = { keys = ["s"], desc = "<scan>", show = true }
save_defaults = { keys = ["ctrl+s"], desc = "<save defaults>", show = true }
clear_cache = { keys = ["x"], desc = "<clear cache>", show = true }
select_up = { keys = ["up", "k", "alt+p"], desc = "<cursor up>", show = false }
select_down = { keys = [
    "down",
    "j",
    "alt+n",
], desc = "<cursor down>", show = false }
